name: "Terraform Cloud trigger run"
description: "Trigger a Terraform Cloud run"
inputs:
  tfe-token:
    description: "The API token granting access to communicate with Terraform Cloud"
    required: true
  organization:
    description: "The organization name containing the workspace to trigger"
    required: true
  workspace:
    description: "The workspace name to trigger"
    required: true
  json-vars:
    description: "JSON-encoded list of variables to update the workspace before triggering the run"
    required: false
    default: "[]"
  message:
    description: "The message to be associated with this run"
    required: false
    default: "Triggered via terraform-cloud-action GitHub Action"
  url:
    description: "The location of the Terraform Cloud installation"
    required: false
    default: "https://app.terraform.io"
  wait:
    description: "If true, will block until the run is marked as completed"
    required: false
    default: "true"
outputs:
  run-id:
    description: "The ID of the created run"
  run-url:
    description: "The URL to view the run"
runs:
  using: "docker"
  image: "docker://ghcr.io/awasilyev/terraform-cloud-action:main"
branding:
  color: blue
  icon: upload-cloud
